VIA_ENABLE 			= yes

SPLIT_KEYBOARD 		= yes
BOOTMAGIC_ENABLE 	= yes

LTO_ENABLE 			= yes
NKRO_ENABLE   		= yes

ENCODER_ENABLE		= yes

EXTRAKEY_ENABLE 	= yes
MOUSEKEY_ENABLE 	= no
COMBO_ENABLE 		= yes
KEY_OVERRIDE_ENABLE = yes